#   _____             _ _           _         
#  |_   _|___ ___ ___|_| |_ ___ ___|_|___ ___ 
#    | | | -_|  _|  _| |  _| . |  _| | -_|_ -|
#    |_| |___|_| |_| |_|_| |___|_| |_|___|___|
#                                           
# Whether or not to print debug lines in the console.
debug: false